name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "Thank you for your pull request. However, you have opened this pull request on a fork of an actively maintained Laravel starter kit. Please open your PR in the original repository."
